### PR TITLE
some patches

### PR DESCRIPTION
**Pull request by whoisrysen**
- added apothecary charcoal to rustic torches, no reason not to make it the same as all other appliances
- changed woodmaker dryad output to raw wood
- (also ran autoformat over the files to fix indents)

### CODE REVIEW

**Comment by tomvd** [comment]
@whoisrysen did you test that dryad output change? I cant test it because I dont have Ideology DLC, and now it throws errors for me.
Also in  Medieval Overhaul there is already a patch for this, if it its not working, better check with them.
I will leave that part of your PR out for now

**Comment by whoisrysen** [comment]
Yes, I did test it. In a separate little mini mod, but same exact setup. Suppose it needs a check somehow to see if that DLC is present. Not sure how to do that, pretty new to this. Could you point me to where you found that existing patch? Skimmed over the MO github and couldn't find anything like that.

**Comment by tomvd** [comment]
https://github.com/SirLalaPyon/MedievalOverhaul/blob/361e088e722fd201faeff91cf2c419199a4ba35d/1.4/Patches/RawLogsRelatedPatches/Replace_WoodLog%20for%20other%20mods.xml#L79

**Comment by tomvd** [comment]
in that code you also see an example how to check for the existence of DLC/mod

**Pull request merged**
